### ISSUE TITLE
How to obtain the Hand Mask for HO3D_v2 evaluation dataset to calculate PSNR metric?

### ISSUE THREAD

**Issue by delaprada** [zijinxuxu/SMHR#2]
Hi! Thanks for providing such a good work.

I wonder how you calculate the psnr score of the evaluation set of HO3D_v2 since HO3D_v2 evaluation set doesn't provide ground-truth hand mask of the images. 

Did you use the predicted render silhouette as the hand mask or generate the ground-truth hand mask using other script?

Thank you very much.

**Comment by zijinxuxu** [comment]
You can find the psnr calculating code here: https://github.com/zijinxuxu/SMHR/blob/63c4196463aeb2321fd9253c80d7701b3c5e3696/lib/models/losses.py#L88

We directly use the rendered mask because GT_Mask is not available in the test set.

**Comment by delaprada** [comment]
> 

I got it. Thank you!
