### ISSUE TITLE
Inquiry about poor results when producing demo on HO3D images

### ISSUE THREAD

**Issue by viridityzhu** [zijinxuxu/SMHR#3]
Hi there,

First of all, I want to express my appreciation for the excellent work you have done!

When producing a demo on HO3D images, I follow your readme to modify the `demo.sh` as:
```
task = 'simplified',dataset='HO3D',Input_RES=224,CHECKPOINTS_PATH='${ROOT}/data/HO3D-2d-simplified.pth', 
comment out #L35 '--pick_hand'
```
where the `HO3D-2d-simplified.pth` is downloaded from the provided link. 

But the results look poor for all test images. The predicted hand is always in the left-up corner:
![image](https://github.com/zijinxuxu/SMHR/assets/39082096/371937e9-502b-421b-93f7-5547cc5fd2d6)

I noticed the warnings that may be causing the problem:
```
loaded HO3D-2d-simplified.pth
Drop parameter mean_theta.
Skip loading parameter p3.weight, required shapetorch.Size([512, 256, 4, 4]), loaded shapetorch.Size([256, 512, 3, 3]).
Skip loading parameter p5.weight, required shapetorch.Size([2048, 256, 8, 8]), loaded shapetorch.Size([2048, 256, 4, 4]).
```

I would greatly appreciate your assistance in resolving this issue. 

Note:
1. I've also tried to modify the input resolution, but it did not solve the problem
2. I tried FreiHAND images using `Single_pho.pth`, and everything looked good.
3. I also tried HO3D images using `Single_pho.pth`, and the results were equally poor:
![image](https://github.com/zijinxuxu/SMHR/assets/39082096/1f928bce-c60a-43d5-af09-1d5730694f6e)

**Comment by zijinxuxu** [comment]
Hello, the models stored in the cloud disk might be from previous versions of the code. During the paper revision period, we have restructured the entire code framework. I suggest that you can train a model on your own using the HO3D dataset, and the training code should work fine.
