### ISSUE TITLE
Inquiry about training FreiHAND

### ISSUE THREAD

**Issue by lsl136** [zijinxuxu/SMHR#4]
Hi! Thanks for providing such a good work.
When I train FreiHAND dataset,I got a issue like ''FileNotFoundError: [Errno 2] No such file or directory: 'outputs/models/rhands_18200.obj'"
I have checked and found that the FreiHAND dataset is complete. Have you encountered this issue？

**Comment by lsl136** [comment]
![issue1](https://github.com/zijinxuxu/SMHR/assets/77133500/0fa4259c-0725-4ad5-baf2-f32d65f2f6b8)

**Comment by zijinxuxu** [comment]
You need to create the output directory like "mkdir -p outputs/models" under the root path before you save the .obj file. And the saved image path "mkdir -p outputs/imgs".
